load("@dwtj_rules_jekyll//jekyll:defs.bzl", "jekyll_website")

jekyll_website(
    name = "my_website",
    config = "_config.yml",
    srcs = [
        "index.markdown",
        "about.markdown",
        "_posts/2020-08-23-welcome-to-jekyll.markdown",
        "404.html",
    ],
    website_source_directory = "my_website",
)